### ISSUE TITLE
"Incompatible client" when using a proxy (eg bungeecord)

### ISSUE THREAD

**Issue by HungryBoy02** [wisp-forest/owo-lib#111]
Hello,

I host a small minecraft server and recently decided to use a proxy to transfer players to our backup server when I had to do maintenance. I have tried Bungeecord, waterfall, and velocity, but all throw the same error when attempting to connect to the server.

This error is of course not thrown when connecting to the server normally. If this is a bug with the mod or potentially a user error, please let me know

**Comment by gliscowo** [comment]
This is caused by owo's handshaking procedure, which proxies do not properly relay by default. If you can use Velocity, simply installing the [owo velocity plugin](https://modrinth.com/plugin/owo-velocity-plugin) is going to completely solve the issue.

If you want to use a different proxy, you need to disable handshake on both server and client by [providing the relevant JVM system property](https://docs.wispforest.io/owo/system-properties/#-dowohandshakedisable-truefalse). The link at the top of that article explains how to do this

I hope this solves your issues - feel free to ask back if you need further assistance

Cheers
