### ISSUE TITLE
owo-lib 1.19.2 keeps crashing

### ISSUE THREAD

**Issue by Pixer14** [wisp-forest/owo-lib#132]
idk why but everytime i play mc with owo-lib in 1.19.2 it always crashes, i read the change log and i saw that the creators fixed it in 1.19.3 0.10.1, can the creators fix this? (i didn't have satin installed with owo-lib, so idk whats cousing this)

**Comment by gliscowo** [comment]
We generally don't backport to older versions of the game, especially not now that we're preparing for 1.19.4.

Furthermore, since you didn't provide the logs or any other form of usable description of what's going wrong, we couldn't try to troubleshoot it even if we had the time.

Either way, I'll be closing this issue as 1.19.2 is long past its support cycle
Cheers
