### ISSUE TITLE
Missing font scaling

### ISSUE THREAD

**Issue by FlorentTomi** [wisp-forest/owo-lib#140]
Hello,

It seems like the component font doesn't scale with the GUI scale.

Example: 
<img width="245" alt="248962987-c4c56190-570c-41a8-87e4-e6e3a1041e5e" src="https://github.com/wisp-forest/owo-lib/assets/5379978/9a5c61d7-1057-47df-b59e-a0dc85c6cf26">

In general, font customization is lacking for most component, whether it's automatic (via GUI scale) or programmatically set.

**Comment by gliscowo** [comment]
I'm genuinely somewhat lost at what you are trying to ask for here. What would you expect the framework to do in this situation? There is literally nothing it could do to componsate other than maybe? scaling down the font and thus the buttons (which I believe is what you're after?) - but that's not a good option for multiple reasons, though primarily because pixel fonts like the one Minecraft uses do not scale well *at all*. 

This is also the reason why font size isn't customizable in general (and, well, the rest of the game also never does this so additionally it would also really out of place), but the entire set of text properties the game supports are right at your fingertips by simply styling the text objects you pass into the components you use.

For your specific situation, I do wonder how this problem occurs in the first place? It seems that you're simply trying to cram way too much UI into much too little space - that's bad both for visuals and UX. The simplest solution, albeit not the most elegant, would be to encapsulate the controls that need more space into a scrollable container, although there are of course also other approaches one might take

Please do enlighten me if I have somehow misunderstood what you're asking for
Cheers

**Comment by FlorentTomi** [comment]
You've answered my question ;).
My point was font customization in general and, in my case, font in button (to scale them down).
I thought it was an issue because the "fill" sizing option was implying, for me at least, that the component would scale down, thus always keeping the same scale relative to the screen (which, if I understand well, is not the entirely the case because of the text scaling).

**Comment by gliscowo** [comment]
As is outlined quite clearly (I believe) [in the docs](https://docs.wispforest.io/owo/ui/component-basics/#sizing), fill-sizing simply makes the component take up whatever percentage of the available space you pass in. If said available space becomes small, the component becomes small

If you have a component in a context where the available space is equal to the screen size, it does indeed behave as you think - but that is not usually the case. Furthermore, it still wouldn't solve the problem but rather make it worse by shrinking the button even further

Cheers
