### ISSUE TITLE
Latest update breaks Sodium's menu in-game (owo-lib-0.11.1+1.20.jar)

### ISSUE THREAD

**Issue by gamerpotion** [wisp-forest/owo-lib#142]
<img src="https://media.discordapp.net/attachments/1077294784877695017/1125772334175895693/image.png" />

**Comment by gliscowo** [comment]
While the problem was comparatively simple to solve this time around, I do find that simply submitting an issues like this without even bothering to write a single sentence with a slightly more detailed explanation and reproduction steps is simply, for lack of a better term, terrible form. 

We developers take a lot of time out of our day to make the mods you are using, and fix issues like these which may pop up - *entirely for free*. It genuinely comes off as quite disrespectful when, in return, you didn't bother to write even just a few words. Nobody expects this to be up to the same standard as a business e-mail - just acknowledge the fact that you are writing a message to the maintainers - fellow humans. You wouldn't simply walk up to someone IRL, show them a picture with a vague-ish description and then walk away, would you?

Thank You

**Comment by gamerpotion** [comment]
<img src="https://www.immunosensation-blog.de/wp-content/uploads/2019/11/COLOURBOX25235053_supplier_224708_medium-1024x684.jpg" />

**Comment by Noaaan** [comment]
Also fixed on Sodiums end, as apparently there was some oversight there: https://github.com/CaffeineMC/sodium-fabric/pull/1873
