### ISSUE TITLE
Owo Lib makes my resource packs fail to load

### ISSUE THREAD

**Issue by ZyDoxx** [wisp-forest/owo-lib#146]
I am using mc 1.20.1 with the latest fabric loader and api.
When I install Owo lib 0.11.0 or 0.11.1 my resource packs won't load anymore.

I am certain it is Owo lib because I've manually tried all mods one by one and only owo lib creates this issue.

I hope this is enough information for a possible fix.

**Comment by Noaaan** [comment]
This is not enough info at all. 

### How to post your logs to get help
https://fabricmc.net/wiki/player:tutorials:logs_ml:windows

**Comment by ZyDoxx** [comment]
I've added my most recent log. 
All mods i use are still added if that's okay.

After trying all combinations it appears owo has problems with both "namepain" and "eating animation" but i'm not 100% sure.
Once it fails it continues to fail after removing all mods except owo.

Hope this helps.

[latest.log](https://github.com/wisp-forest/owo-lib/files/12061043/latest.log)

**Comment by Dragon-Seeker** [comment]
Due to Namepains' more closed-source nature, it may be better to use something like [Neat](https://www.curseforge.com/minecraft/mc-mods/neat-fabric-quilt) as it dose a similar thing with less jank. Overall the mod dose a overwrite which is hard to work around to say the least and frankly the close source nature makes it near impossible to support. Recommend send a issue a report or switching to a different mod.

**Comment by gliscowo** [comment]
As already explained by @Dragon-Seeker, this is not on owo's side - it's a problem caused by how Name Pain implements its functionality in a highly incompatible and frankly unneccessary manner. You may well try to report to the issue to them and see if they are up for fixing it. Otherwise there's not much we can do

Cheers
