### ISSUE TITLE
owo lib makes game crash with optifabric

### ISSUE THREAD

**Issue by Kevengg** [wisp-forest/owo-lib#147]
on load the game gives the error: Resource reload failed. it than works as normal until it finishes loading the a world and starts to render. it so hangs for a second and crashes directly to desktop.

this is somewhat similar to what https://github.com/wisp-forest/owo-lib/issues/146 describes, but with a different shader engine

Crash report: 
[crash-2023-07-15_21.24.01-client.txt](https://github.com/wisp-forest/owo-lib/files/12062627/crash-2023-07-15_21.24.01-client.txt)

Log file:
[latest.log](https://github.com/wisp-forest/owo-lib/files/12062629/latest.log)

*Edit:
Forgot to mention, tested this with the different mods in the mod collection, only owo lib triggered this error

**Comment by Dragon-Seeker** [comment]
This frankly isn't much of a issue to fix as mods like Iris and Sodium exist. I would highly recommend using that instead since optifine isn't a great mod to have compat for in general.

**Comment by Kevengg** [comment]
I am not familiar with Iris or Sodium, so il have to look at that, thanks for the recommendation

**Comment by gliscowo** [comment]
As mentioned by @Dragon-Seeker, trying to maintain compatibility with OptiFabric is quite the chore (given that OptiFine is closed-source) and just frankly not worth it since more or less every OptiFine feature has been replicated by open-source, less incompatible mods

You can check out [this article](https://lambdaurora.dev/optifine_alternatives/) for an overview of what you can use

Thus, I'll go ahead and close this issue
Cheers
