### ISSUE TITLE
[1.20] OwoDebugCommands makes owo lib no longer able to be server-side only

### ISSUE THREAD

**Issue by Lama3L9R** [wisp-forest/owo-lib#148]
As the title mentioned, in io.wispforest.owo.command.debug.OwoDebugCommands, registered a command with argument type namespace `owo` making it no longer able to be server-side only.

Maybe we should consider changing the argument type to String

**Comment by gliscowo** [comment]
I don't think this is particularly relevant since, well, the debug commands are only registered in debug mode (and owo really isn't intended for serverside use anyway). If you want to prevent this, simply [disable debug mode](https://docs.wispforest.io/owo/system-properties/#-dowodebug-truefalse)

Cheers
