### ISSUE TITLE
Incompatability between OwoItemGroup tabs and Just Enough Items

### ISSUE THREAD

**Issue by Noaaan** [wisp-forest/owo-lib#177]
As seen in https://github.com/Noaaan/MythicMetals/issues/178

JEI seems to populate its recipe viewer by looking at items in creative groups. This causes some weirdness with owo-lib and its tabbed itemgroups, as only the items from the current selected tab is loaded when JEI reloads. I have reproduced this in the following way:
- Join a world where you have a tabbed owo-itemgroup with custom items
- Check JEI, as its missing some items
- Select another tab
- Rejoin the world to reload JEI, the items are now replaced 

I am not familiar with JEI code, so unsure what the fix to this is. From previous internal discussions JEI could in theory grab the items from elsewhere, even within itemgroups, which should always hold all the items of the group. We could also in theory make explicit compat for supplying the items somehow, although the scope of that is unknown to me.

**Comment by gliscowo** [comment]
There isn't much (if anything) that can be done on owo's side regarding this problem - the creative tab must necessarily report the items the way it does in order to, well, work. All items of all tabs get reported in the search tab stacks however (`getSearchTabDisplayItems` in Mojmap) - the proper fix here in my opinion is for JEI to query those instead of the normal tab stacks

As such, it's probably advisable to open an issue on their side and forward this information

**Comment by Noaaan** [comment]
Closing as this issue is fixed
