### ISSUE TITLE
oWo > handshake failure incompatible server

### ISSUE THREAD

**Issue by Sodz1aX** [wisp-forest/owo-lib#188]
I want to make server with mythic metals and other mods but when i join it showed the kinda an error that's says: oWo > handshake failure incompatible server. I don't know why, version of owo is the same on the client and the server. Can someone help?

**Comment by gliscowo** [comment]
As I assume you have probably figured out, this error means that your client cannot connect to a compatible version of owo on your server. From our experience with people setting up new servers, this usually happens because you are simply not running th server correctly - often people accidentally run a vanilla server instead of a fabric one. 

If you have made sure this is not the case, please do send us the `latest.log` of both the server and client so we can look into your specific case further

Cheers

**Comment by Sodz1aX** [comment]
[latest (1).log](https://github.com/wisp-forest/owo-lib/files/13201408/latest.1.log)
[latest.log](https://github.com/wisp-forest/owo-lib/files/13201409/latest.log)

**Comment by Sodz1aX** [comment]
bro how many days i must wait, i want play with friends

**Comment by Noaaan** [comment]
The logs you provided didn't really reveal anything in particular that points to an error. The only thing I could imagine is causing this problem is fabricproxy_lite, as proxies in the past has proven to interfere with the handshaking process (for example Velocity, which we do support via a plugin, see the link below).

I would advice you to try to disable the proxy on your server/remove that mod and see if it helps. If not, you might want to consider disabling handshake entirely, which you can find information about here: https://docs.wispforest.io/owo/system-properties/#-dowohandshakedisable-truefalse

**Comment by Sodz1aX** [comment]
I don't understand half of the content in this link. I don't know where to put this plugin, but if I put it somewhere, how should I configure it?

**Comment by Noaaan** [comment]
The plugin is only relevant if you are using Velocity, which assuming from your logs you aren't. If you *are using it*, then I believe you would simply install this like any other mod. I recommend trying to remove `fabricproxy` first, and see if it solves your issue.

In regards to Java System Properties, the additional strings you use before running your server, there are numerous guides on the internet on how to apply these to your server. One of these is included in the linked documentation on the first paragraph of the page. 

If you are using a server hosting provider, you might need to contact them in order to get these changed. Its case-by-case whether they allow you to change these yourself.

**Comment by Sodz1aX** [comment]
i deleted the file fabric proxy but nothing happens and the file returns

**Comment by Sodz1aX** [comment]
so what should I do

**Comment by gliscowo** [comment]
Since handshake is now disabled in production by default as of 0.12.0, I'll go ahead and close this issue. If you still need help setting up a server, feel free to leave another comment here or come ask for assistance on Discord

Cheers

**Comment by AshdoII** [comment]
> Since handshake is now disabled in production by default as of 0.12.0, I'll go ahead and close this issue. If you still need help setting up a server, feel free to leave another comment here or come ask for assistance on Discord
> 
> Cheers

May I ask how should I disable handshake in 1.20.1, the laest mod version is 0.11.4.

**Comment by Noaaan** [comment]
https://docs.wispforest.io/owo/system-properties/#-dowohandshakedisable-truefalse

**Comment by Max173Shironin** [comment]
> https://docs.wispforest.io/owo/system-properties/#-dowohandshakedisable-truefalse

Hello. Please write the instructions for this method. I tried to open these files in different programs, but I couldn't find the line that fixes problem. I think I'm not the only one with this, please help

**Comment by Ristovski** [comment]
@Max173Shironin Read the very first sentence of https://docs.wispforest.io/owo/system-properties/ and check out the "Java System Properties" link.

**Comment by Max173Shironin** [comment]
> @Max173Shironin Read the very first sentence of https://docs.wispforest.io/owo/system-properties/ and check out the "Java System Properties" link.

I read the contents of the links, but I don’t understand what to do. I ask you to write instructions for dummies, please)

**Comment by Max173Shironin** [comment]
...

**Comment by AshdoII** [comment]
Would a 0.12.0 version for 1.20.1 be possiable?I add -Dowo.handshake.disable=true to environment variables of my launcher and my server starting .bat file, there is 95% chance that it doesn't work.

**Comment by jacklollz2** [comment]
Connecting to a NanoLimbo server as a hub on Velocity, I receive this error message. I shouldn't. It is a Limbo server, a hub. This hub is used as a gateway to go to a different server that has all of the Fabric mods.
