### ISSUE TITLE
Incompatibility with 23w45a

### ISSUE THREAD

**Issue by JerryHan3** [wisp-forest/owo-lib#192]
Game failed to launch when only loading this mod with fabric api v0.90.8 in snapshot 23w45a. 

The log is presented here: https://mclo.gs/4nMlRHD

~~Don't ask me why I'm trying to load this mod in a snapshot ver - I just want to render isometric images of new blocks and mobs~~

**Comment by Dragon-Seeker** [comment]
The given max target version is given on the jar itself with such being 1.20.2 meaning you can not expect such to at all work on snapshots of the game even if such seems to load. Due to the changes that have occurred, owo will need to wait for the final release to work on supporting 1.20.3/1.21 but such has yet to occur.
