### ISSUE TITLE
Mixin transformation of io.wispforest.owo.mixin.itemgroup.CreativeInventoryScreenMixin failed

### ISSUE THREAD

**Issue by ninjaguardian** [wisp-forest/owo-lib#193]
When I go into gmc and press E to open my inventory, it crashes.

https://pastebin.com/safpdaVT

**Comment by gliscowo** [comment]
Is this a prebuilt modpack you're playing or something custom? If it's a prebuilt, you might wanna try just reinstalling it - otherwise you'll need to find the conflicting mod in your set (assuming that this is a compatibility issue in that case, which I find likely since nobody else has reported a problem like this)

Either way, we've stopped providing active support for 1.19.2 versions of our mods a long time ago - we have a lot projects to manage and only limited time to do so, we simply don't have the capacity to chase freak problems on outdated builds. Feel free to come back here if you have further questions, but I can't guarantee we'll be able to help you out

Cheers

**Comment by ninjaguardian** [comment]
It was a prebuilt that I changed and updated. But I lost the pack so I won't be able to figure things out. You can close this if you want.
