### ISSUE TITLE
[Bug] ButtonComponent force cast DrawContext to OwoUIDrawContext in**vailla** method renderWidget

### ISSUE THREAD

**Issue by zly2006** [wisp-forest/owo-lib#203]
This is a method inherited from vanilla, force casting it may be problematic.

https://github.com/wisp-forest/owo-lib/blob/c5a0700262761a7494d442a4474f0654b9274da5/src/main/java/io/wispforest/owo/ui/component/ButtonComponent.java#L40-L42

**Comment by gliscowo** [comment]
While this is technically true, using owo-ui components outside an owo-ui component tree is (for obvious reasons) not supported. Since the `DrawContext` instance in an owo-ui tree will always be an `OwoUIDrawContext` I believe this is a fine compromise to make - besides just reimplementing buttons entirely there's not much that can be done to alleviate this otherwise

If you have any suggestions (or could maybe explain why this relevant to you) let me know, otherwise I'll go ahead and close this
Cheers

**Comment by zly2006** [comment]
OK, thanks for your explanation.
