### ISSUE TITLE
I think this is owo lib crash

### ISSUE THREAD

**Issue by ZerJ704** [wisp-forest/owo-lib#215]
I start the game and it crash. I use it for extra enchantment mod. Minecraft Fabric 1.20.4

Crash.log: https://gist.github.com/ZerJ704/f9a5dbb0e7a4db88e08e1873cb3d6a01
Latest.log: https://gist.github.com/ZerJ704/a3a1bce998f518e1af1b1f742b078608

**Comment by Noaaan** [comment]
I do not believe this issue is valid. 
- You are using multiple mods marked for 1.20.2, which are usually not cross-compatible with 1.20.3/1.20.4.
 - This includes owo - You would want to upgrade it to 0.12.3.
- Your crash seems to be coming from Extra Enchantments and Curses, which includes Reach Entity Attributes. I suspect that version of it does not support latest. Looking at their mod page only their Forge builds support 1.20.4. Their Fabric versions only support 1.20.2

**Comment by ZerJ704** [comment]
> I do not believe this issue is valid.
> 
> * You are using multiple mods marked for 1.20.2, which are usually not cross-compatible with 1.20.3/1.20.4.
> * This includes owo - You would want to upgrade it to 0.12.3.
> * Your crash seems to be coming from Extra Enchantments and Curses, which includes Reach Entity Attributes. I suspect that version of it does not support latest. Looking at their mod page only their Forge builds support 1.20.4. Their Fabric versions only support 1.20.2

oh my god my bad, why tf I read it 1.20.4 for that mod. Im really sorry for this.
