### ISSUE TITLE
1.20.1 Quilt Latest Version Causes Inventory Scrollbar To Appear Invisible

### ISSUE THREAD

**Issue by PolyframeX** [wisp-forest/owo-lib#221]
When going in the search creative inventory tab, the scrollbar is not rendering, and is invisible.

Minecraft Version: 1.20.1
Quilt Version: 0.24.0
QFAPI 7.5.0
QSL 6.1.2

Logs: [latest.log](https://github.com/wisp-forest/owo-lib/files/14813353/latest.log)

**Comment by PolyframeX** [comment]
After experimenting more. This issue seems to be hard to know its exact cause. As some of my friends are not able to reproduce it.

**Comment by gliscowo** [comment]
This exact bug was fixed in `0.11.2` as witnessed by multiple testers while preparing for BlanketCon '23. Given that you're having trouble reproducing it, there's probably a more complex cause than simply owo-lib - unless you can give us a reproduction case I'm afraid there's not much we can do

Cheers

**Comment by PolyframeX** [comment]
Ah I see, when I have the time I'll maybe look for a mod incompatibility or something.
