### ISSUE TITLE
crashed on startup!)

### ISSUE THREAD

**Issue by zc1108aaa** [wisp-forest/owo-lib#236]
[latest.log](https://github.com/wisp-forest/owo-lib/files/15257583/latest.log)
[crash-2024-05-09_12.31.42-client.txt](https://github.com/wisp-forest/owo-lib/files/15257585/crash-2024-05-09_12.31.42-client.txt)

**Comment by gliscowo** [comment]
You're using an outdated version of owo-lib (0.12.0+1.20.3) which is not compatible with 1.20.6. Instead, use [0.12.8+1.20.5](https://modrinth.com/mod/owo-lib/version/0.12.8+1.20.5)

Cheerse

**Comment by zc1108aaa** [comment]
![image](https://github.com/wisp-forest/owo-lib/assets/155424398/1daab5cb-7435-483d-9eb3-b50b8a90957d)
This mod is automatically installed

**Comment by zc1108aaa** [comment]
![image](https://github.com/wisp-forest/owo-lib/assets/155424398/1daab5cb-7435-483d-9eb3-b50b8a90957d)
This mod is automatically installed

**Comment by Noaaan** [comment]
Due to large changes with items, any mod made for 1.20.3 might not be compatible with 1.20.5+. If the mod is labelled to be compatible, but they ship/include the wrong version of owo-lib, then they need to update it.

You can always manually install the latest version of owo-lib yourself, which would override the older versions bundled with these mods
