### ISSUE TITLE
[incompatibility report]: currently conflict with the mod [silent"s delight]

### ISSUE THREAD

**Issue by wrctera** [wisp-forest/owo-lib#238]
my game version is 1.20.1 fabric 0.15.11 latest
when owo-lib use with silent's delight, game ui will disapear and the glowing effect's outline sketches will also loss.
IDK what happening within them. what i can do is just report this issue to both sides  😂
PLS try 2 fix!!!❤

**Comment by gliscowo** [comment]
We need some more information to be able to help here, especially your game's `latest.log` - as outlined [in our contributing guidelines](https://github.com/wisp-forest/.github/blob/5dff6a3cc8567a95f8d72e3d0cc852a7f2db7364/CONTRIBUTING.md#before-contributing)

**Comment by abby-cadabra** [comment]
Hello, just want to add that I've experienced this same problem. Took me a full day of binary searching to figure it out. Not sure whether the problem is with Silents Delight or owo-lib, but I can confirm that the UI disappears when both are installed.

To me it seems like the UI might be "crashing" somehow, since it appears normal for a few seconds after logging in, before quickly disappearing. But I'm no expert.

This is my latest.log while the error was happening, but I couldn't see anything interesting in there: https://cfpaste.modularity.gg/paste/?content=768367574001778729_1252879593983971498&filename=latest.log&raw=false

Have attached two screenshots that show with and without silents delight installed. I am also on Fabric, 1.20.1.

![2024-06-19_16 44 39](https://github.com/wisp-forest/owo-lib/assets/132413818/701f1b36-d9d1-4348-a75e-257f959921f9)
![2024-06-19_16 44 43](https://github.com/wisp-forest/owo-lib/assets/132413818/d3f8ca0c-c859-42e0-9be3-a3a97ef8acda)

**Comment by wrctera** [comment]
Seems like the newest silents delight had fix this bug, so this issue could be close.
