### ISSUE TITLE
Crash when booting up after the first run

### ISSUE THREAD

**Issue by BugRod** [wisp-forest/owo-lib#244]
Pretty sure it worked the first time but not after that.
Server crash log https://mclo.gs/tSuUoi0
My client crash log is attached to this report
[crash-2024-06-09_10.04.41-client.txt](https://github.com/user-attachments/files/15752911/crash-2024-06-09_10.04.41-client.txt)

**Comment by BugRod** [comment]
I realized that I had 1.20.3 owo but I  changed it to 1.20.5 owo but it still crashed 
[crash-2024-06-09_10.04.41-client.txt](https://github.com/user-attachments/files/15752922/crash-2024-06-09_10.04.41-client.txt)

**Comment by gliscowo** [comment]
The crash in the second log you sent is caused by SpruceUI, not owo-lib. In fact, according to the log, owo isn't even being loaded in that instance. Thus I'll conclude your initial problem was indeed just an incorrect owo version - feel free to reopen the issue if this turns out not to be the case

Cheerse
