### ISSUE TITLE
Handshake Failure

### ISSUE THREAD

**Issue by GettingTechnicl** [wisp-forest/owo-lib#25]
I attempted to use this numerous times running on Fabric in a docker container. Each time I get handshake failure incompatible client. As soon as the plugin is removed everything works fine. 

Steps to reproduce issue -
Deploy docker of itzg/minecraft-server:latest
Type = FABRIC
launcher = 0.10.2
Loader = 0.14.4

have this mod install and start server
once server is started you will not be able to connect due to handshake failure.

**Comment by gliscowo** [comment]
Have you made sure that your client is compatible? As in, it has the same mods with the same versions installed as the server? In this case I would believe that you don't have owo installed on the client, since a `incompatible client` error without a description should only happen if the client is missing owo. If you client is in fact compatible, the Docker image is probably configured in some really strange way that stops the packets from arriving, in which case I would have to check it manually - but first please verify that your client is in fact compatible
Cheers

**Comment by GettingTechnicl** [comment]
I did not see anything in requirements that stated the client needed to have OWO installed, that is most likely the issue. My apologies and thanks for the fast response.
