### ISSUE TITLE
Incompatibility with Vulkan mod

### ISSUE THREAD

**Issue by RegulusSource** [wisp-forest/owo-lib#93]
Vulkan mod uses vulkan engine for Mc-rendering, error occurs when I enable both owolib and vulkanmod

**Comment by gliscowo** [comment]
While this behavior does in fact occur, it is not something we can or will even attempt to fix. Vulkan is a fundamentally different graphics API, and a significant number of parts in owo are written for OpenGL and OpenGL only - unless we start supporting two different graphics APIs concurrently (one of which is not even available 98% of the time) this is something we cannot fix

**Comment by AlexanderwithaA** [comment]
Has the situation on this issue changed? Both mods have gone through quite a few changes since this issue was opened. Reading this issue it seems that the game used to immediately crash when both VulkanMod and owo lib were installed, now however it only crashes when trying to open a config screen using owo lib. So, if it could be fixed that'd be greatly appreciated.
