### ISSUE TITLE
Add deprecated tooltip for options annotated with @Deprecated

### ISSUE THREAD

**Issue by Awakened-Redstone** [wisp-forest/owo-lib#96]
It would be nice to show a `Deprecated option` message for options annotated with `@Deprecated`
_On my code I show it before the restart required message_

For example like this:
![image](https://user-images.githubusercontent.com/40528665/217602276-15c91ac4-06c8-4e48-8c82-75abaf97125b.png)
![image](https://user-images.githubusercontent.com/40528665/217602964-a3ed2fe1-f9de-4193-948d-b58af0d64177.png)

Translation used:
```json
"text.owo.config.deprecated": [
    {
        "text": "⚠",
        "color": "#EB1D36"
    },
    " ",
    {
        "text": "This option is deprecated",
        "color": "gray"
    }
]
```

**Comment by gliscowo** [comment]
After some consultation with the team, we don't think that this is really a good idea for the library itself. The primary reason for this is that it does not tell the user any further information on *why* this option is deprecated and what they should use instead. This makes for a terrible user experience - you're simply being told that "no, this is bad" without any further explanation.

This then leads to the reason why we don't see this feature as necessary. Because an additional explanation would always have to be provided via the lang file anways (that is, via the option's `.tooltip` key), you can simply include the deprecation notice with this explanation, and there is no reason to support this in code. 

We can however see about incorporating the translation you offered into owo's lang file to make it easy to include via a `{ "translate": ... }` component

Cheers
